import Link from "next/link";
import { useState, type ChangeEvent } from "react";
import type { Property } from "@/features/explorer/types/property";
import type { CameraConfig, Hotspot } from "@/features/explorer/types/property";
import { ExteriorCameraPreview } from "./ExteriorCameraPreview";
import { VisualCameraEditor } from "./VisualCameraEditor";

export function PropertyReviewEditor({ property, onChange }: { property: Property; onChange: (property: Property) => void }) {
  const [detectedCamera] = useState<CameraConfig>({ position: [...property.cameraPresets[0].camera.position], target: [...property.cameraPresets[0].camera.target] });
  const [draftCamera, setDraftCamera] = useState<CameraConfig>({ position: [...property.cameraPresets[0].camera.position], target: [...property.cameraPresets[0].camera.target] });
  const [isEditingCamera, setIsEditingCamera] = useState(false);
  const updateRoom = (index: number, field: "name" | "floorId", value: string) => onChange({ ...property, rooms: property.rooms.map((room, roomIndex) => roomIndex === index ? { ...room, [field]: value } : room) });
  const updateCamera = (axis: number, value: number) => setDraftCamera((current) => ({ ...current, position: current.position.map((item, itemIndex) => itemIndex === axis ? value : item) as [number, number, number] }));
  const applyCamera = () => onChange({ ...property, cameraPresets: property.cameraPresets.map((preset, index) => index === 0 ? { ...preset, camera: draftCamera } : preset) });
  const saveHotspot = (hotspot: Hotspot) => onChange({ ...property, hotspots: [...property.hotspots, hotspot] });
  const resetCamera = () => setDraftCamera({ position: [...detectedCamera.position], target: [...detectedCamera.target] });
  return <div className="review-editor"><header><span>Detected structure</span><strong>Edit before publishing</strong></header><div className="review-room-list">{property.rooms.map((room, index) => <div key={room.id}><input aria-label={`Room ${index + 1} name`} value={room.name} onChange={(event: ChangeEvent<HTMLInputElement>) => updateRoom(index, "name", event.target.value)} /><select aria-label={`${room.name} floor`} value={room.floorId} onChange={(event) => updateRoom(index, "floorId", event.target.value)}>{property.floors.map((floor) => <option key={floor.id} value={floor.id}>{floor.name}</option>)}</select></div>)}</div><div className="camera-editor-intro"><div><span>Exterior camera</span><strong>Set it visually first.</strong><p>Compose the view on the model, then use manual coordinates only for fine tuning.</p></div><button className="creation-primary" type="button" onClick={() => setIsEditingCamera(true)}>Edit in 3D →</button></div><details className="manual-camera-controls"><summary>Manual coordinates <span>Advanced</span></summary><fieldset><legend>Exterior camera position</legend>{["X", "Y", "Z"].map((label, axis) => <label key={label}><span>{label}</span><input aria-label={`Camera ${label} position`} type="number" step="0.1" value={draftCamera.position[axis]} onChange={(event) => updateCamera(axis, Number(event.target.value))} /></label>)}</fieldset></details><ExteriorCameraPreview modelUrl={property.modelUrl} camera={draftCamera} propertyName={property.name} /><p className="camera-preview-help">The frame reflects the pending view. Apply it only when it looks right.</p><div className="camera-preview-actions"><button type="button" onClick={resetCamera}>Reset to detected view</button><Link href={`/explore/${property.id}`} onClick={applyCamera}>Open full 3D preview ↗</Link><button className="creation-primary" type="button" onClick={applyCamera}>Apply exterior view →</button></div>{isEditingCamera && <VisualCameraEditor modelUrl={property.modelUrl} propertyName={property.name} initialCamera={draftCamera} detectedCamera={detectedCamera} rooms={property.rooms} onSave={setDraftCamera} onSaveHotspot={saveHotspot} onClose={() => setIsEditingCamera(false)} />}</div>;
}
