"use client";

import Link from "next/link";
import type { ChangeEvent } from "react";
import { Brand } from "@/components/brand/Brand";
import { FormField } from "@/components/forms/FormField";
import { CaptureCard } from "../components/CaptureCard";
import { CreationProgress } from "../components/CreationProgress";
import { ProcessingPipeline } from "../components/ProcessingPipeline";
import { PropertyReviewEditor } from "../components/PropertyReviewEditor";
import { usePropertyCreation } from "../hooks/usePropertyCreation";

export function PropertyCreationScreen() {
  const flow = usePropertyCreation();
  const canContinue = flow.draft.title.trim() && flow.draft.location.trim();
  const isProcessing = ["uploading", "validating", "queued", "reconstructing", "optimizing"].includes(flow.status);
  if (!flow.hydrated) return <main className="creation-shell route-loading"><span>Restoring your property draft</span></main>;
  return <main className="creation-shell"><header className="creation-header"><Link href="/"><Brand /></Link><span>Property model studio</span><Link href="/">Saved locally · Exit</Link></header><CreationProgress current={flow.step} />
    {flow.step === "details" && <section className="creation-layout"><div className="creation-intro"><span>01 · Property details</span><h1>Tell us what<br />we are rebuilding.</h1><p>These details shape the capture checklist and become the foundation of the published property listing.</p></div><form className="creation-form" onSubmit={(event) => { event.preventDefault(); if (canContinue) flow.setStep("capture"); }}><FormField label="Property name" placeholder="e.g. Courtyard House" value={flow.draft.title} onChange={(event: ChangeEvent<HTMLInputElement>) => flow.setDraft({ ...flow.draft, title: event.target.value })} required /><FormField label="Location" placeholder="e.g. Lekki, Lagos" value={flow.draft.location} onChange={(event: ChangeEvent<HTMLInputElement>) => flow.setDraft({ ...flow.draft, location: event.target.value })} required /><FormField label="Description" rows={4} placeholder="Architecture, materials and notable features" value={flow.draft.description} onChange={(event: ChangeEvent<HTMLTextAreaElement>) => flow.setDraft({ ...flow.draft, description: event.target.value })} /><div className="creation-form-row"><FormField label="Bedrooms" type="number" min={1} max={20} value={flow.draft.bedrooms} onChange={(event: ChangeEvent<HTMLInputElement>) => flow.setDraft({ ...flow.draft, bedrooms: Number(event.target.value) })} /><FormField label="Floors" type="number" min={1} max={10} value={flow.draft.floors} onChange={(event: ChangeEvent<HTMLInputElement>) => flow.setDraft({ ...flow.draft, floors: Number(event.target.value) })} /></div><button className="creation-primary" disabled={!canContinue}>Build capture plan <span>→</span></button></form></section>}
    {flow.step === "capture" && <section className="capture-section"><div className="capture-heading"><div><span>02 · Guided capture</span><h1>Give the model enough<br />information to be believable.</h1></div><div className="coverage-meter"><strong>{flow.coveragePercent}%</strong><span>Required coverage</span><i><b style={{ width: `${flow.coveragePercent}%` }} /></i></div></div><aside className="capture-note"><strong>For better reconstruction</strong><p>Use overlapping photos, keep doors open, avoid moving people, and walk continuously between connected rooms.</p></aside><div className="capture-grid">{flow.coverage.map((requirement) => <CaptureCard key={requirement.id} requirement={requirement} files={flow.files.filter((file) => file.category === requirement.id)} onAdd={flow.addFiles} onRemove={flow.removeFile} />)}</div><div className="creation-actions"><button onClick={() => flow.setStep("details")}>← Back</button><button className="creation-primary" onClick={() => flow.setStep("validate")}>Check coverage <span>→</span></button></div></section>}
    {flow.step === "validate" && <section className="validation-section"><div><span>03 · Coverage report</span><h1>{flow.missing.length ? "A few spaces need more context." : "Your capture set is ready."}</h1><p>{flow.missing.length ? "Add the missing angles below before generating a production model. You may continue with the preview generator to test the workflow." : "The capture set meets the recommended minimum for a connected reconstruction."}</p></div><div className="validation-card"><header><strong>{flow.coveragePercent}%</strong><span>Capture confidence</span></header>{flow.coverage.map((item) => <div key={item.id}><span>{item.count >= item.minimum ? "✓" : "!"}</span><strong>{item.label}</strong><small>{item.minimum === 0 ? "Optional" : `${item.count} of ${item.minimum} supplied`}</small></div>)}</div><div className="creation-actions"><button onClick={() => flow.setStep("capture")}>← Add more media</button><button className="creation-primary" disabled={isProcessing} onClick={flow.generate}>{isProcessing ? "Processing…" : "Generate property preview"}<span>→</span></button></div></section>}
    {flow.step === "review" && flow.result && <><section className="review-section"><div className="review-copy"><span>04 · Review</span><h1>{flow.status === "published" ? "Your property is ready to share." : "Your first model is ready to inspect."}</h1><p>The generated record has its own property ID, room data, floor assignments and camera configuration. The model asset remains a preview proxy until reconstruction is connected.</p><dl><div><dt>Rooms detected</dt><dd>{flow.result.roomCount}</dd></div><div><dt>Model confidence</dt><dd>{flow.result.confidence}%</dd></div><div><dt>Status</dt><dd>{flow.status}</dd></div></dl><div className="review-actions"><Link className="creation-primary" href={`/explore/${flow.result.propertyId}`}>Review in 3D <span>↗</span></Link>{flow.status !== "published" && <button onClick={flow.publish}>Publish property</button>}<button onClick={flow.startOver}>New property</button></div></div><div className="review-model"><span>Generated model · {flow.result.propertyId}</span><div className="review-house"><i /><i /><b /></div><strong>{flow.result.property.name}</strong><small>{flow.result.property.location}</small></div></section><section className="review-editor-section"><div><span>Property configuration</span><h2>Correct what the model inferred.</h2><p>Room labels, floor assignments and the exterior camera are stored with this property and immediately used by its explorer route.</p></div><PropertyReviewEditor property={flow.result.property} onChange={flow.updateProperty} /></section></>}
    <ProcessingPipeline status={flow.status} />
  </main>;
}
