import Image from "next/image";
import Link from "next/link";
import { Brand } from "@/components/brand/Brand";

const jobs = [
  { name: "Courtyard House", place: "Lekki, Lagos", status: "Generating model", time: "18 min ago", image: "/images/courtyard-house.webp" },
  { name: "Ridge House", place: "Aburi, Ghana", status: "Ready to review", time: "1 hr ago", image: "/test-captures/coastal-curve-villa/01-exterior-front.png" },
  { name: "Palm Residence", place: "Kokrobite, Ghana", status: "Upload paused", time: "2 hr ago", image: "/test-captures/coastal-curve-villa/02-exterior-rear.png" },
];

export function StudioDashboardScreen() {
  return <main className="studio-dashboard"><aside className="studio-sidebar"><Link href="/"><Brand /></Link><nav><Link aria-current="page" href="/studio">Properties</Link><Link href="/studio/new">Create property</Link><a href="#guide">Capture guide</a></nav><div className="studio-profile"><strong>Amara Okafor</strong><span>North & Coast Realty</span><Link href="/">↗&nbsp;&nbsp;Back to website</Link></div></aside><section className="studio-main"><header className="studio-heading"><div><h1>Your properties</h1><p>Prepare, review and publish interactive homes.</p></div><div className="studio-tools"><label><span className="sr-only">Search properties</span><input placeholder="Search properties" /></label><Link href="/studio/new">Create property</Link></div></header><div className="studio-overview"><article className="studio-featured"><div className="studio-featured-image"><Image src="/test-captures/coastal-curve-villa/01-exterior-front.png" alt="Coastal Curve Villa" fill priority sizes="(max-width: 900px) 100vw, 58vw" /></div><div className="studio-featured-meta"><div><h2>Coastal Curve Villa</h2><p>Ada Foah, Ghana <i /> Needs one connecting view <span>14 photos · Updated 12 min ago</span></p></div><Link href="/studio/new">Continue capture</Link></div></article><section className="studio-jobs"><h2>In progress</h2>{jobs.map((job) => <Link href="/studio/new" className="studio-job" key={job.name}><span className="studio-job-image"><Image src={job.image} alt="" fill sizes="150px" /></span><span><strong>{job.name}</strong><small>{job.place}</small><b className={job.status === "Upload paused" ? "is-paused" : ""}>{job.status}</b><small>{job.time}</small></span><i>→</i></Link>)}</section></div><section className="studio-published"><h2>Published</h2><div><article><Image src="/test-captures/courtyard-house/03-living-room.png" alt="Cliffside Retreat" fill sizes="50vw" /><span><strong>Cliffside Retreat</strong><Link href="/explore/demo-house">View live property →</Link></span></article><article><Image src="/images/courtyard-house.webp" alt="Lantern House" fill sizes="50vw" /><span><strong>Lantern House</strong><Link href="/explore/demo-house">View live property →</Link></span></article></div></section></section></main>;
}
